[project]
name = "dostoevsky-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "natsort==7.0.1",
    "numpy==1.26.4",
    "pandas==1.5.3",
    "xlrd>=2.0.1",
]
